-- Asset Table
CREATE TABLE asset (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       customer_id VARCHAR(50) NOT NULL,
                       asset_name VARCHAR(50) NOT NULL,
                       size DECIMAL(19,4) NOT NULL,
                       usable_size DECIMAL(19,4) NOT NULL,
                       CONSTRAINT uq_asset UNIQUE (customer_id, asset_name)
);
